#version: '3'
#services:
#  # Application Dockerfile is in same folder which is .
#  app:
#    build: .
#    command: ["java","ProjectTeam2.App"]
#
#
#  # db is is db folder
#  db:
#    build: db/.
#    restart: always
#    ports:
#      - "33061:3306"
#
version: '3.3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "33061:3306"