name: World Data Querying with JAVA/SQL
on: push

jobs:
  build:
    name: Querying Action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run Unit Tests
        run: mvn -Dtest=UnitTest.AppTest test
      - name: Package the application and run Docker Compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit

