name: Java Querying  App
on: push
jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'
      - name: Unit Tests
        run: mvn -Dtest=UnitTest.SpecificPopulationReportTest test -DfailIfNoTests=false
  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'
      - name: Integration Tests
        run: |
          docker build -t database ./db
          docker run --name world -dp 33061:3306 database
          mvn -Dtest=IntegrationTest.AppIntegrationTest test
          docker stop world
          docker rm world
          docker image rm database

  build:
    name: Build and Start Using docker-compose and run app
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'
      - name: Package and Run docker compose
        run: |
          mvn package
          docker compose up --abort-on-container-exit


