name: World Data Querying with JAVA/SQL
on: push

jobs:
  build:
    name: Querying Action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run Unit Tests
        run: mvn -Dtest=UnitTest.* test

      - name: Package the application and run Docker Compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit
